renames = {}

renames["2019Dec"] = {
        "Cypher" : "cypher",
        "Kittens" : "kittens",
        "donka" : "donka",
        "fX-Boo7y" : "booty",
        "murkey@nodiscord:(" : "murkey",
        "nigel" : "nigel",
        "reker" : "reker",
        "spaztik" : "spaztik",
        "Ra!ser" : "raiser",
        "Lunatic ????" : "luna",
        "John_Mullins" : "john_mullins",
        "FisterMiagi" : "deadeye",
        "$kr1lla" : "scrilla",
        "DillWeed" : "dillweed",
        "SOURCE" : "source",
        "murkey" : "murkey",
        "DeadBalls" : "deadeye",
        "parcher" : "parcher",
        "Elsa Hosk" : "elsa",
        "Gutz0rzzz" : "gut",
        "eXe|Boo7y" : "booty",
        "BabY YoDA" : "raiser",
        "The Ladies Man" : "ladiesman",
        "bru" : "bru",
        "MoistSurgeon" : "moistsurgeon",
        "audzine" : "audzine",
        "Fisterimpeachme" : "deadeye",
        "P.I.M.P." : "pimp",
        "Chris Gutwin" : "gut",
        "corpse" : "corpse",
        "vees" : "vis",
        "Lovjee_fan" : "Lovjee_fan",
        "Ra!sMerrYxMAS!" : "raiser",
        "[>>] P.I.M.P." : "pimp",
        "lutka" : "lutka",
        "wolfbaggins tommy" : "tragic",
        "Wang of Pain" : "wang"
        }

renames["2020Feb"] = {
        ".:.c@k-el" :  "cakel",
        ".:.CORPSE" :  "corpse",
        ".:.festus" :  "festus",
        ".:.spaztik" :  "spaztik",
        "[>>] Cliffdark" :  "cliffdark",
        "[tTt]c@k-el" :  "cakel",
        "Aimtastic Shootej" :  "aimtastic",
        "bru" :  "bru",
        "bwat" :  "bwat",
        "caffbe bryant" :  "caffeine",
        "CubanPete" :  "cubanpete",
        "Cypher" :  "cypher",
        "Deadeye" :  "deadeye",
        "DeadEye" :  "deadeye",
        "DHS Cypher" :  "cypher",
        "DHS DeadEye" :  "deadeye",
        "DHS Fistermiagi" :  "deadeye",
        "DHS jaytee" :  "jaytee",
        "DHS REKER" :  "reker",
        "DHS TOMMYTURBO" :  "tragic",
        "DHS tRAGIC" :  "tragic",
        "DillWeed" :  "dillweed",
        "donka" :  "donka",
        "eternal_" :  "eternal",
        "eXe|Anialatem" :  "mean",
        "eXe|Boo7y" :  "booty",
        "eXe|Flogzero" :  "flogzero",
        "FisterMiagi" :  "deadeye",
        "garT" :  "tragic",
        "huckleb rek" :  "reker",
        "HuckleBerryTommy" :  "tragic",
        "Joep" :  "joep",
        "John_Mullins" :  "john_mullins",
        "Kittens" :  "kittens",
        "MoistSurgeon" :  "moistsurgeon",
        "N/A BRND" :  "brandon",
        "N/A CKY" :  "cky",
        "n/a donkey" :  "donkey",
        "N/A DONKZ" :  "donka",
        "n/a eternal" :  "eternal",
        "N/A Ra!ser" :  "raiser",
        "n/a ra!ser" :  "raiser",
        "n00b" :  "n00b",
        "nigel" :  "nigel",
        "parcher" :  "parcher",
        "Ra!ser" :  "raiser",
        "rastareker" :  "reker",
        "rastatommy" :  "tragic",
        "Reflex cfg <3" :  "reflex",
        "RekeR :P" :  "reker",
        "scrill4" :  "scrilla",
        "SnowRunGut" :  "gut",
        "SOURCE" :  "source",
        "spaztik" :  "spaztik",
        "tragiC" :  "tragic",
        "Trinity*c@k-el" :  "cakel",
        "Trinity*festus" :  "festus",
        "Trinity*spaztik" :  "spaztik",
        "tTt->festus" :  "festus",
        "vodka!" :  "vodka"
        }

renames["2020Jan"] = {
        "Cliffdark" :  "cliffdark",
        "Cypher" :  "cypher",
        "DillWeed" :  "dillweed",
        "FisterMiagi" :  "deadeye",
        "Kittens" :  "kittens",
        "P.I.M.P. 180" :  "pimp",
        "Ra!ser" :  "raiser",
        "SOURCE" :  "source",
        "donka" :  "donka",
        "eXe|Boo7y" :  "booty",
        "elsa" :  "elsa",
        "murkey" :  "murkey",
        "reker" :  "reker",
        "spaztik" :  "spaztik",
        "illkilla" :  "illkilla",
        "nigel" :  "nigel",
        "eXe|Anialatem" :  "mean",
        "John_Mullins" :  "john_mullins",
        "[>>] Cliffdark" :  "cliffdark",
        "aaa" :  "parcher",
        "fromiam" :  "fro",
        "-[x]-nigel" :  "nigel",
        "-[x]-spaztik" :  "spaztik",
        "prowler*" :  "prowler",
        "eternal_" :  "eternal",
        "-[x]-DeadEye" :  "deadeye",
        "Festus_of_Pain" :  "festus",
        "MoistSurgeon" :  "moistsurgeon",
        "TK|POW" :  "tkpow",
        "BlewTHAT" :  "raiser",
        "The Ladies Man" :  "ladiesman",
        "Marcus Mariguta" :  "gut",
        "parcher" :  "parcher",
        "eX*Festus" :  "festus",
        "SKOL|Boo7y" :  "booty",
        "Wang of Pain" :  "wang",
        ".:.c@k-el" :  "cakel",
        ".:.prowler" :  "prowler",
        ".:.spaztik" :  "spaztik",
        "eXe|Flogzero" :  "flogzero",
        ".:.Festus" :  "festus",
        "tragiC" :  "tragic",
        "Fistermiagi" :  "deadeye",
        "Hucklebericus" :  "deadeye",
        "c@k-el" :  "cakel",
        "mach1ne" :  "machine",
        "o/ spaztik" :  "spaztik",
        "corpse" :  "corpse",
        "Tittens" :  "tragic",
        ".:.festus" :  "festus",
        "cKy" :  "cky"
        }

renames["2020Mar"] = {
        "!tH!Gut" : "gut",
        "#REDUE John_Mullins" : "john_mullins",
        "-=prowler=-" : "prowler",
        "-Tv-Ra!ser" : "raiser",
        "-eh-brian" : "brian",
        "-n2p)(spaztik" : "spaztik",
        ".:.Flogzero" : "flogzero",
        ".:.c@k-el" : "cakel",
        ".:.crops" : "corpse",
        ".:.festus" : "festus",
        ".:.prowler" : "prowler",
        ".:.spaztik" : "spaztik",
        "BRND REDUE" : "brandon",
        "Cliff of Pain" : "cliffdark",
        "CoronaDill" : "dillweed",
        "Cypher" : "cypher",
        "DHS DEADEYE" : "deadeye",
        "DHS Fistermiagi" : "deadeye",
        "DHS NIGEL" : "nigel",
        "DHS jaytee" : "jaytee",
        "DHS tragiC" : "tragic",
        "DUBARD <o/" : "dubard",
        "Deadeye" : "deadeye",
        "DillWeed" : "dillweed",
        "Festus" : "festus",
        "Fister of Pain" : "deadeye",
        "HuckleBerryTragic" : "tragic",
        "Jimmy" : "jimmy",
        "John_Mullins" : "john_mullins",
        "John_Mullins_of_Pain" : "john_mullins",
        "Kittens" : "kittens",
        "MoistSurgeon" : "moistsurgeon",
        "N/A BRND" : "brandon",
        "N/A Ra!ser" : "raiser",
        "N/A donkz" : "donka",
        "Pasek" : "pasek",
        "Pasek*" : "pasek",
        "Pk of Pain" : "pasek",
        "RAISER" : "raiser",
        "Raiser" : "raiser",
        "SCRILL4" : "scrilla",
        "SOURCE" : "source",
        "Uber Brian" : "kotip",
        "Wang of Pain" : "wang",
        "Yaourt ! ?" : "yaourt",
        "[>>] Cliffdark" : "cliffdark",
        "[>>] Helga von Bulow" : "cliffdark",
        "afk-ternal" : "eternal",
        "bru" : "bru",
        "c@k-el" : "cakel",
        "caffbe bryant" : "caffeine",
        "coronaBRND" : "brandon",
        "dillweed" : "dillweed",
        "donka" : "donka",
        "donkz" : "donka",
        "donkz of  Pain" : "donka",
        "donkztik" : "donka",
        "eXe|Anialatem" : "mean",
        "eXe|Flogzero" : "flogzero",
        "eXe|MeaN" : "mean",
        "eXe|Meanguine" : "mean",
        "eternal_" : "eternal",
        "fisterMiagi" : "deadeye",
        "fromiam" : "fro",
        "fucker" : "raiser",
        "miLes" : "miles",
        "miles" : "miles",
        "miles of Pain" : "miles",
        "mooshu" : "mooshu",
        "murkey" : "murkey",
        "n/a SOURCE" : "source",
        "n/a eternal" : "eternal",
        "n00b" : "brandon",
        "nig of Pain" : "nigel",
        "nigel" : "nigel",
        "parcher" : "parcher",
        "parhcer" : "vis",
        "prowler" : "prowler",
        "reker" : "reker",
        "rekernator" : "reker",
        "roz'murkey" : "murkey",
        "roz'parcher" : "parcher",
        "shootz" : "shootz",
        "source" : "source",
        "spaz of pain" : "spaztik",
        "spaztik" : "spaztik",
        "sscasper" : "casper",
        "tTt-c@k-el" : "cakel",
        "tTt-festus" : "festus",
        "tTt-prowler" : "prowler",
        "teker" : "tragic",
        "v57-sOn4R*" : "sonar",
        ">> Risk!" : "risk",
        "BRND" : "brandon",
        "BoN, Dtto" : "ditto",
        "FisterMiagi" : "deadeye",
        "Flogzero" : "flogzero",
        "Joep" : "joep",
        "LuNa" : "luna",
        "MEAN" : "mean",
        "Raiser clark" : "raiser",
        "TommyTomorrow" : "tragic",
        "boydarilla" : "boydarilla",
        "c@k kent" : "cakel",
        "caff stark" : "caffeine",
        "festus" : "festus",
        "vodka!" : "vodka",
        "tTt-spaztik" : "spaztik",
        "Boydarilla" : "boydarilla",
        "DHS LUNA" : "luna",
        "brujah" : "bru",
        "caff eating" : "caffeine",
        "flogzero" : "flogzero",
        "jaytee***" : "jaytee",
        "kick gut" : "gut",
        "nigel**" : "nigel",
        "raiser" : "raiser",
        "woodChop" : "woodchop"
        }

renames["2020Apr"] = {
        ".:.prowler" : "prowler",
        "Cliffdark" : "cliffdark",
        "DillWeed" : "dillweed",
        "Jimmy" : "pasek",
        "Kittens" : "kittens",
        "NABRND" : "brandon",
        "SOURCE" : "source",
        "bru" : "bru",
        "eXe|Boo7y" : "booty",
        "eXe|Flogzero" : "flogzero",
        "eXe|MeaN" : "mean",
        "eXe|eternal" : "eternal",
        "miles" : "miles",
        "murkey" : "murkey",
        "not13KDAMAGE" : "raiser",
        "parcher" : "parcher",
        "risk" : "risk",
        "spaztik" : "spaztik",
        "tragiC" : "tragic",
        "-playa-" : "playa",
        "Gutzwrzynski" : "gut",
        "Lunatic ????" : "luna",
        "Oops" : "oops",
        "Ra!sa" : "raiser",
        "caff ********" : "caffeine",
        "eXe|donka" : "donka",
        "eXe|prowler" : "prowler",
        "eternal" : "eternal",
        "kotip" : "kotip",
        "paper" : "paper",
        "rozmurk3y" : "murkey",
        "shrek" : "shrek",
        "#REDUE John_Mullins" : "john_mullins",
        "*** Cliffdark" : "cliffdark",
        "*** DozA" : "doza",
        "*** chinamann" : "chinamann",
        "*** sOnAR. <o/" : "sonar",
        "*** schwien" : "schwien",
        "-eh-brian" : "brian",
        ".:.spaztik" : "spaztik",
        "@blackmagik" : "blackmagik",
        "BRND" : "brandon",
        "Boydarilla" : "boydarilla",
        "Cock-El" : "parcher",
        "Cypher" : "cypher",
        "DHS Fistermiagi" : "deadeye",
        "DHS jaytee" : "jaytee",
        "FisterMiagi" : "deadeye",
        "Joep" : "joep",
        "Paint:>" : "paint",
        "RAZERRA!SER" : "raiser",
        "Ra!ser" : "raiser",
        "SCRILL4" : "scrilla",
        "SpuddyBuddy" : "spuddy",
        "TK|POW" : "tkpow",
        "Wang of Pain" : "wang",
        "[>>] Cliffdark" : "cliffdark",
        "aristotle" : "aristotle",
        "blackmagiknc." : "blackmagik",
        "c@k-3l" : "cakel",
        "c@k-el" : "cakel",
        "c@k-el*" : "cakel",
        "d13 caff" : "caffeine",
        "donka" : "donka",
        "donkz" : "donka",
        "eXe|Prowler" : "prowler",
        "festus" : "festus",
        "festusmoelesac" : "festus",
        "flogzero" : "flogzero",
        "gutzzzz" : "gut",
        "jaytee**************" : "jaytee",
        "mooshu" : "mooshu",
        "naper" : "naper",
        "nigel" : "nigel",
        "nigel ***" : "nigel",
        "nigel**" : "nigel",
        "playa" : "playa",
        "proWler" : "prowler",
        "prowler" : "prowler",
        "reker" : "reker",
        "spuddy" : "spuddy",
        "traggart" : "tragic",
        "trag|c" : "tragic",
        "notvis" : "vis",
        "vodka!" : "vodka",
        "-Tv-Ra!ser" : "raiser",
        "c@kztik" : "cakel",
        "-Tv-Conscious*" : "conscious",
        "corpse" : "corpse",
        "blackmagik" : "blackmagik",
        ".=[AoH]BlAZ" : "blaz",
        "jaytee*****" : "jaytee",
        "Ra!ser*" : "raiser",
        "c@k-el***" : "cakel",
        "Flogzero" : "flogzero",
        "OLIOKATH" : "oliokath",
        "RekeR" : "reker",
        "Festusmoesac" : "festus",
        "Cliffdark***" : "cliffdark",
        "mooshu*" : "mooshu",
        "nigel***" : "nigel",
        "trag|C" : "tragic",
        "MeaN" : "mean",
        "knifey" : "knifey",
        "[>>] jaytee" : "jaytee",
        "C0RPSE" : "corpse",
        "CAFF D13" : "caffeine",
        "not blackvis" : "vis",
        "oIiokath" : "oliokath",
        "rekernator" : "reker",
        "woodChop" : "woodchop",
        "Ra!ser ???" : "raiser",
        "brian" : "brian",
        "Ex-)Festus" : "festus",
        "VENOM" : "venom",
        "Euclid" : "euclid",
        "mooshu sux" : "mooshu",
        "eXe|Ra!se" : "raiser",
        "SPEC nigel" : "nigel",
        "fistermiagi" : "deadeye",
        "gut" : "gut",
        "raiser" : "raiser",
        "Tier B Ra!ser" : "raiser",
        "Tier C Jimmy" : "pasek",
        "Tier C c@k" : "cakel",
        "Tier C miles" : "miles",
        "valor-conscious*" : "conscious",
        "Tier C Fistermiagi" : "deadeye",
        "TIER F kotip" : "kotip",
        "Fistermiagi" : "deadeye",
        "bluemagik" : "blackmagik",
        "jaytee'" : "jaytee",
        "gutz0rz" : "gut",
        "Misha X" : "elsa",
        "Conscious*" : "conscious",
        "TIER C SPAZTIK" : "spaztik",
        "nigel." : "nigel",
        "f0nz3*" : "fonze",
        "HyperNegatiVemaN" : "HyperNegatiVemaN",
        "troll fans" : "reflex",
        "// Jimmy" : "pasek",
        "c@kzero" : "cakel",
        "fonze*" : "fonze",
        "c@k" : "cakel"
        }
renames["2020May"] = {
        "@corpse," : "corpse",
        "@jaytee" : "jaytee",
        "Jimmy" : "pasek",
        "MeaN" : "mean",
        "Ra!ser..." : "raiser",
        "beast" : "beast",
        "bru" : "bru",
        "eXe|Flogzero" : "flogzero",
        "fromiam" : "fro",
        "murkey" : "murkey",
        "nigel" : "nigel",
        "prowler" : "prowler",
        "Conscious*" : "conscious",
        "fonze" : "fonze",
        "FisterMiagi" : "deadeye",
        "Kittens" : "kittens",
        "blackmagik" : "blackmagik",
        "c@k-el" : "cakel",
        "donka" : "donka",
        "miles" : "miles",
        "oIiokath" : "oliokath",
        "Dr3sserWo0d!" : "dresserwood",
        "#REDUE John_Mullins" : "john_mullins",
        "DozA" : "doza",
        "festus" : "festus",
        "kindergarden c@k" : "cakel",
        "spaztik" : "spaztik",
        "vodka!" : "vodka",
        "*** Cliffdark" : "cliffdark",
        "Dress3rWo0d!" : "dresserwood",
        "fonze*" : "fonze",
        "blackmagiknc." : "blackmagik",
        "*Conscious'gA" : "conscious",
        "paper" : "paper",
        "eXe|MeaN" : "mean",
        "*Conscious'" : "conscious",
        "Jimmy Bones" : "pasek",
        "corpse" : "corpse",
        "valor-conscious*" : "conscious",
        "pixi" : "pixi",
        "Ra!ser" : "raiser",
        "-n2p)(spaztik-" : "spaztik",
        "$upac@k" : "cakel",
        "c@ktens" : "cakel",
        "asianjaytee" : "jaytee",
        "Jimbo" : "pasek",
        "siTtIns" : "corpse",
        "conscious*" : "conscious",
        "Ra!ser -_-" : "raiser",
        "Anialatem" : "mean",
        "Flogzero" : "flogzero",
        "Pixi" : "pixi",
        "Ra!ser-D" : "raiser",
        "blackmagik)" : "blackmagik",
        "dresserwood!" : "dresserwood",
        "mooshu" : "mooshu",
        "eternal)" : "eternal",
        "spaztik*" : "spaztik",
        "trag|c*" : "tragic",
        "sscasper" : "casper",
        "eXe|Anialatem" : "mean",
        "@festus" : "festus",
        "(503th.esla)" : "elsa",
        "parcher" : "parcher",
        "prwlr-$mG" : "prowler",
        "virus047" : "virus",
        "Cypher" : "cypher",
        "eXe|Folgzero" : "flogzero",
        "eelsa" : "elsa",
        "milse" : "miles",
        "rampage !!!!" : "rampage",
        "caff 23" : "caffeine",
        "playa" : "playa",
        "eternal" : "eternal",
        "Oops" : "oops",
        "reker" : "reker",
        "DillWeed" : "dillweed",
        "MoistSurgeon" : "moistsurgeon",
        "Tittens" : "tragic",
        "Becky G" : "elsa",
        "Cliffdark" : "cliffdark",
        "MILES" : "miles",
        "paper*" : "naper",
        "tragiC" : "tragic",
        "Luna" : "luna",
        "mooshu@" : "mooshu",
        "@eternal)" : "eternal",
        "CORPSE" : "corpse",
        "jaytee" : "jaytee",
        "BRU" : "bru",
        "kotip" : "kotip",
        "prowl3r" : "prowler",
        "dresserwood" : "dresserwood",
        "blackmagik(d)" : "blackmagik",
        "purples.Jimbo" : "pasek",
        "cK aimO" : "aimology",
        "(Daria.Skyhigh)" : "elsa",
        "-d-blackmagik" : "blackmagik",
        "TE)(spaztik" : "spaztik",
        "-a-Ra!ser-)" : "raiser",
        "m|Volks" : "volks",
        "[>>] Daria Cross" : "cliffdark",
        "-a-Ra!ser" : "raiser",
        "[>>] Cliffdark" : "cliffdark",
        "CAFF 23" : "caffeine",
        "Flogzero..." : "flogzero",
        "Mean" : "mean",
        "OIiokath" : "oliokath",
        "donkalabtop" : "donka",
        "gutzzz*" : "gut",
        "trag|c" : "tragic",
        "eternal_" : "eternal",
        "SOURCE" : "source",
        "c@xt0r" : "cakel",
        "n00b" : "noob",
        "MOOSHU" : "mooshu",
        "c@k" : "cakel",
        "dwood" : "woodchop",
        "magik" : "blackmagik",
        "noncefonze" : "fonze",
        "traggart" : "tragic",
        "Joep!" : "joep"
        }

renames["2020MayDraft"] = {
        "8===DBRU" : "bru",
        "8===DFONZ" : "fonze",
        "8===DKittens" : "kittens",
        "8===DMLS" : "miles",
        "8==DFistermiagi" : "deadeye",
        "@blackmagik" : "blackmagik",
        "@c@k-el" : "cakel",
        "@corpse" : "corpse",
        "@eternal)" : "eternal",
        "@festus" : "festus",
        "@nigel" : "nigel",
        "8===DOIiO" : "oliokath",
        "REDUE-Cypher" : "cypher",
        "REDUE-Jimmy" : "pasek",
        "REDUE-Spaztik" : "spaztik",
        "Ra!ser" : "raiser",
        "Redue-Conscious*" : "conscious",
        "Redue-Flogzero" : "flogzero",
        "donka" : "donka",
        "murkey" : "murkey",
        "pixi" : "pixi",
        "rekernator" : "reker",
        "traggart" : "tragic",
        ":+:VirUs047`" : "virus",
        "meaN" : "mean",
        "REDUE-Prowler" : "prowler",
        "Redue-Ra!ser-D^" : "raiser",
        "8===DillWeed" : "dillweed",
        "8===Dknifey" : "knifey",
        "8===DoIiokath" : "oliokath",
        "Dimension" : "dimension",
        "MeaN" : "mean",
        "gart" : "tragic",
        "reker" : "reker",
        "virus" : "virus",
        "8==DFisterMiagi" : "deadeye",
        "beast" : "beast",
        "Redue-Cypher" : "cypher",
        "Redue-Elsa" : "elsa",
        "Redue-Jimmy" : "pasek",
        "Redue-Ra!ser" : "raiser",
        "Redue-Spaztik" : "spaztik",
        "@corpse'" : "corpse",
        "@fromiam" : "fro",
        "@jaytee" : "jaytee",
        "vodka!" : "vodka",
        "[>>] Cliffdark" : "cliffdark"
        }

renames["2020Jun"] = {
        "Julie Skyhigh" : "elsa",
        "conscious*" : "conscious",
        "eXe|Flogzero" : "flogzero",
        "fonze*" : "fonze",
        "magik" : "blackmagik",
        "miles" : "miles",
        "murkey" : "murkey",
        "prowler" : "prowler",
        "spaztik" : "spaztik",
        "$upac@k" : "cakel",
        "FisterMiagi" : "deadeye",
        "Ra!ser-D" : "raiser",
        "SOURCE" : "source",
        "Cypher" : "cypher",
        "Lunatic ????" : "luna",
        "caff 23" : "caffeine",
        "Flogzero" : "flogzero",
        "jaytee" : "jaytee",
        "nigel." : "nigel",
        "playa" : "playa",
        "c@kzero" : "cakel",
        "BLM Becky G" : "elsa",
        "DillWeed" : "dillweed",
        "Fistermiagi" : "deadeye",
        "donka" : "donka",
        "parcher" : "parcher",
        "bru" : "bru",
        "lastplace!" : "dresserwood",
        "fonze" : "fonze",
        "MEAN" : "mean",
        "trag|c" : "tragic",
        "Kittens" : "kittens",
        "#REDUE John_Mullins" : "john_mullins",
        "c@k kent" : "cakel",
        "fromiam" : "fro",
        "c@k-el" : "cakel",
        "MILES" : "miles",
        "festus" : "festus",
        "BLM caff" : "caffeine",
        "eternal_" : "eternal",
        "valor-Jaytee" : "jaytee",
        "CONSCIOUS*" : "conscious",
        "JOEP" : "joep",
        "KITTENS" : "kittens",
        "MOOSHU" : "mooshu",
        "MURKEY" : "murkey",
        "eternal" : "eternal",
        "fromon" : "fro",
        "NIGEL" : "nigel",
        "vidderz" : "vid",
        "mooshu" : "mooshu",
        "tragiC" : "tragic",
        "gutzorzzz" : "gut",
        "reker" : "reker",
        "BRND" : "brandon",
        "MLS" : "miles",
        "vodka!" : "vodka",
        "-DozA-" : "doza",
        "LLM Becky G" : "elsa",
        "dresserwood" : "dresserwood",
        "pixi" : "pixi",
        "eXe|Boo7y" : "booty",
        "DeadPool" : "deadeye",
        "c@kmas" : "cakel",
        "eXe|MeaN" : "mean",
        "n!g-el" : "nigel",
        "ScumBag" : "scumbag",
        "TEAM MILES LLM" : "elsa",
        "c@k-el*" : "cakel",
        "TEAM MILES donka" : "donka",
        "TEAM MILES fro" : "fro",
        "TEAM MILES miles" : "miles",
        "MIcaffLES" : "caffeine",
        "TEAM MILES Fister" : "deadeye",
        "caff" : "caffeine",
        "OIiokath" : "oliokath",
        "TEAM MILES BRU" : "bru"
        }

renames["2020Jul"] = {
        "$upac@k" : "cakel",
        "GorthraX" : "gorthrax",
        "SOURCE" : "source",
        "Wang of Pain" : "wang",
        "conscious*" : "conscious",
        "eternal_" : "eternal",
        "spaztik" : "spaztik",
        "DillWeed" : "dillweed",
        "donka" : "donka",
        "nigel" : "nigel",
        "FisterMiagi" : "deadeye",
        "Kittens" : "kittens",
        "bruttens" : "bru",
        "eXe|Flogzero" : "flogzero",
        "miles" : "miles",
        "nittens" : "nigel",
        "parcher" : "parcher",
        "pixi" : "pixi",
        "spittens" : "spaztik",
        "fISTERmIAGI" : "deadeye",
        "John_Mullins" : "john_mullins",
        "FisterMiarcher" : "parcher",
        "fonze" : "fonze",
        "jaytee" : "jaytee",
        "mosalah" : "fro",
        "magik" : "blackmagik",
        "Jimmy69" : "pasek",
        "Ra!ser-D" : "raiser",
        "++ eternal" : "eternal",
        "MOLAR caff" : "caffeine",
        "TONSIL miles" : "miles",
        "blacklivesmagik" : "blackmagik",
        "murkey" : "murkey",
        "rob" : "rob",
        "eternal" : "eternal",
        "BRND" : "brandon",
        "ROB" : "rob",
        "c@k-el" : "cakel",
        "CONSCIOUS*" : "conscious",
        "flogzero..." : "flogzero",
        "fromon" : "fro",
        "LASHERBOOM" : "lasher",
        "WolfPlayer17" : "playa",
        "murkey :)" : "murkey",
        "(tE)Cypher" : "cypher",
        "isco" : "isco",
        "nigel |]" : "nigel",
        "SPAZTIK" : "spaztik",
        "fistermiagi" : "deadeye",
        "ckap" : "ckap",
        "GART" : "tragic",
        "fonze :>" : "fonze",
        "luna :o" : "luna",
        "miles 8/" : "miles",
        "vidderz" : "vid",
        "bru" : "bru",
        "eXe|MeaN" : "mean",
        "FisterMiaguns" : "deadeye",
        "Flogzero" : "flogzero",
        "Miles_Mullins" : "miles",
        "Virus047" : "virus",
        "c@k_mullins" : "cakel",
        "caff_mullins" : "caffeine",
        "corpse_MullInS" : "corpse",
        "fonze_mullins" : "fonze",
        "nigel_mullins" : "nigel",
        "oiiokath" : "oliokath",
        "-__- eternal" : "eternal",
        "Du$t3r.com" : "duster",
        "ETERNAL" : "eternal",
        "valor-conscious*" : "conscious",
        "free parch caff" : "caffeine",
        "free parch fonze" : "fonze",
        "free parch kittens" : "kittens",
        "free parch murkey" : "murkey",
        "Lunatic ????" : "luna",
        "coRpse" : "corpse",
        "F0nz3" : "fonze",
        "Luna" : "luna",
        "corpse" : "corpse",
        "garT" : "tragic",
        "rekernator" : "reker",
        "** dash" : "dash",
        "eXe|Boo7y" : "booty",
        "corPse" : "corpse",
        "Fistermiagi" : "deadeye",
        "KRAZYKAZE" : "krazykaze",
        "WolvE" : "wolve",
        "Fonze" : "fonze",
        "QQ Boo7y" : "booty",
        "Becky G" : "elsa",
        "Cypher" : "cypher",
        "Du$t3r" : "duster",
        "Festus" : "festus",
        "WarRi0R" : "warrior",
        "krazykaze?" : "krazykaze",
        "sajla" : "sajla",
        "aristotle" : "aristotle",
        "cure4cancer" : "cure4cancer",
        "BRND*" : "brandon",
        "cKy." : "cky",
        "caffeine bran" : "caffeine",
        "nigel*" : "nigel",
        "o/ fonze" : "fonze",
        "o/ spaztik" : "spaztik",
        "Apoculos*" : "apoculos",
        "BIRD-CATKitty" : "BIRD-CATKitty",
        "Fistermiagi*" : "deadeye",
        "Paint:>" : "paint",
        "bru*" : "bru",
        "fonze*" : "fonze",
        "haii:D" : "haii",
        "miles*" : "miles",
        "2POWS" : "parcher",
        "3POWS" : "miles",
        "FisterMiagi*" : "deadeye",
        "SOURCE:>" : "source",
        "bru:>" : "bru",
        "conscious*:>" : "conscious",
        "murkey:>" : "murkey",
        "nigel:>" : "nigel",
        "sala:>" : "sala",
        "sloth" : "sloth",
        "caffcher" : "caffeine",
        "spaztik:>" : "spaztik",
        "u$a RETARD" : "end",
        "!ban eternal" : "eternal",
        "CobraCommanderNinja" : "parcher",
        "notmiles" : "miles",
        "!ban sala" : "sala",
        "sala" : "sala",
        "Shrek 2 on DVD" : "parcher",
        "n!kon" : "nikon",
        "oIiokath" : "oliokath",
        "warping.murkey" : "murkey",
        "dresserwood" : "dresserwood",
        "noteternal" : "eternal",
        "Conscious*" : "conscious",
        "Kitten" : "kittens",
        "Noob1" : "scrilla",
        "brujah" : "bru",
        "cKy" : "cky",
        "donkah" : "donka",
        "fonzeE" : "fonze",
        "festus" : "festus",
        "BriannN" : "sa-brian",
        "blackmagik" : "blackmagik",
        "mooshu" : "mooshu",
        "caffeine_birdz" : "caffeine",
        "JAYtee" : "jaytee",
        "f'/FisterMiagi" : "deadeye",
        "f'ngl" : "nigel",
        "f'onz" : "fonze",
        "f'src" : "source",
        "ghvst" : "elusive",
        "sloth !!!" : "sloth",
        "f'WarRi0R" : "warrior",
        "fromon:O(" : "fro",
        "jayzee" : "jaytee",
        "Du5t3r" : "duster",
        "Donkey" : "donkey",
        "ETERNAL)" : "eternal",
        "FATiHHOTTTTTTTT" : "firehot",
        "xeRo" : "xero",
        "tittyboi" : "warrior",
        "LLDEF Cliffdark" : "cliffdark"
        }

renames["2020Quakecon"] = {
        "CORPSE|KrN" : "corpse",
        "Cypher !!!" : "cypher",
        "Luna|KrN" : "luna",
        "Sonid" : "sonid",
        "caff !!!" : "caffeine",
        "miles !!!" : "miles",
        "rampage !!!" : "rampage",
        "reker|KrN" : "reker",
        "scrill4|KrN" : "scrill4",
        "sloth !!!" : "sloth",
        "spuddy|KrN" : "spuddy",
        "tragic|KrN" : "tragic",
        "makL !!!" : "makl",
        "mooshu !!!" : "mooshu",
        "./TrL]$kr1lla*" : "$kr1lla",
        "./TrL]Argento*" : "argento",
        "./TrL]Cholo*" : "cholo",
        "./TrL]Croma*" : "croma",
        "./TrL]Festus*" : "festus",
        "./TrL]Peru*" : "peru",
        "stOmp|c@k-el" : "cakel",
        "stOmp|conscious" : "conscious",
        "stOmp|fonze*" : "fonze",
        "stOmp|pixi" : "pixi",
        "stOmp|siluro" : "siluro",
        "stOmp|spaztik" : "spaztik",
        "fenix" : "fenix",
        "Du5t3r" : "duster",
        "S!A Desk1ciao" : "desk1ciao",
        "SIA BLAZK" : "blaz",
        "S|A Fox" : "fox",
        "S|A Snipercat" : "snipercat",
        "S|A v1RKES" : "virkes",
        "S|A Ka!ser" : "raiser",
        "S|A iLufi" : "ilufi",
        "flagrant/BRND" : "brandon",
        "flagrant/Fistermiagi" : "deadeye",
        "flagrant/Kittens" : "kittens",
        "flagrant/bru" : "bru",
        "flagrant/nigel" : "nigel",
        "flagrant/source" : "source",
        "sonic !!!" : "sonic",
        "flagrant/WarRi0R" : "warrior",
        "!tH!BBQFrito" : "bbqfrito",
        "!tH!FaYgo" : "faygo",
        "!tH!Yo*J-Dawg" : "yojdawg",
        "!tH!d4nK" : "d4nk",
        "!tH!gut*" : "gut",
        "!tH!xeRo" : "xero",
        ">Danzail" : "danzail",
        ">blox" : "blox",
        ">dash" : "dash",
        ">nosy" : "nosy",
        ">pengu" : "pengu",
        ">spdr" : "spdr",
        "!tH!Grit" : "grit",
        "Ceres(/)" : "ceres",
        "VoRg(/)" : "vorg",
        "VtmN(/)" : "vtmn",
        "sixers(/)" : "sixers",
        "sonix(/)" : "sonix",
        "yyz(/)" : "yyz",
        "BLATANT Flogzer" : "flogzero",
        "BLATANT Hotdamn" : "elusive",
        "BLATANT cKy." : "cky",
        "BLATANT candy(" : "candy",
        "BLATANT eternal" : "eternal",
        "BLATANT murkey" : "murkey",
        "BLATANT Donkey-" : "donkey",
        "BLATANT John_Mu" : "john_mullins",
        "playa|KrN" : "playa",
        "flagrant/Kitten" : "kittens",
        "flagrant/WarRi0" : "warrior",
        ".VippiN" : "vippin",
        ".dozer" : "dozer",
        ".haste" : "haste",
        ".loknlowd" : "loknlowd",
        ".ringo" : "ringo",
        ".tofu" : "tofu",
        "BLATANT Donkey" : "donkey",
        "BLATANT Flogzero..." : "flogzero",
        "BLATANT candy:>" : "candy",
        "BLATANT eternal)" : "eternal",
        "BLATANT hdx)" : "elusive",
        "BLATANT murkey:)" : "murkey",
        "BLATANT crono:cooldude:" : "john_mullins",
        "st0mp|magik" : "blackmagik",
        "makL^  !!!" : "makl",
        "./TrL]aristotle*" : "aristotle",
        "./TrL]fenix*" : "fenix",
        ">pingrage" : "pingrage",
        "f'BRND" : "brandon",
        "f'Kittens" : "kittens",
        "f'WarRi0R" : "warrior",
        "f'bru" : "bru",
        "f'nigel" : "nigel",
        "f'src" : "source",
        "f'knifey" : "knifey",
        "BLATANT crono:c" : "john_mullins",
        "murkey" : "murkey",
        "FLAY BRND" : "brandon",
        "FLAY BRU" : "bru",
        "FLAY Kittens" : "kittens",
        "FLAY NGL" : "nigel",
        "FLAY SOURCE" : "source",
        "FLAY WARRI0R" : "warrior",
        "f'FisterMiagi" : "deadeye",
        "!tH!Je$t" : "jest",
        "!tH!Yo*j-Dawg" : "yojdawg",
        "!tH!gut*******" : "gut",
        "FLAY FISTERMIAG" : "deadeye",
        "FLAY KNIFEY" : "knifey",
        "!tH!d4nk" : "d4nk",
        "tragiC|KrN" : "tragic",
        "virus|KrN" : "virus",
        "Blackout(/)" : "blackout",
        "VtmN" : "vtmn",
        "luna|KrN" : "luna",
        "SpuddyBuddy" : "spuddy",
        "st0mp|dwoood!" : "dresserwood",
        "playa|krn" : "playa",
        }

renames["2020Aug"] = {
        "BLATANT candy(" : "candy",
        "Elver" : "elver",
        "F'Fistermiagi" : "deadeye",
        "Kittens" : "kittens",
        "LASHERBLAST" : "lasher",
        "WarRi0R" : "warrior",
        "miles" : "miles",
        "PARCHERBUME" : "parcher",
        "brujah" : "bru",
        "eXe|Flogzero" : "flogzero",
        "f'BRND" : "brandon",
        "ERRORYIKES" : "erroryikes",
        "BLATANT Donkey" : "donkey",
        "MILESSQUIRT" : "miles",
        "cure" : "cure4cancer",
        "John_Mullins" : "john_mullins",
        "LOco<.<Festus" : "festus",
        "aristotle" : "aristotle",
        "bru" : "bru",
        "f'ngl" : "nigel",
        "$kr1lla" : "$krilla",
        "CORPSE|KrN" : "corpse",
        "cure4cancer" : "ceres",
        "Conscious*" : "conscious",
        "Claudia" : "elsa",
        "Festus" : "festus",
        "fromiam" : "fro",
        "karen" : "karen",
        "FLAY FISTERMIAGI" : "deadeye",
        "FLAY Kittens" : "kittens",
        "SOURCE" : "source",
        "donka" : "donka",
        "parcher" : "parcher",
        "st0mp|magik" : "blackmagik",
        "stOmp|c@k-el" : "cakel",
        "stOmp|fonze*" : "fonze",
        "stOmp|spaztik" : "spaztik",
        "FLAY BRND" : "brandon",
        "BLATANT cKy." : "cky",
        "Fnigel" : "nigel",
        "ShaT" : "shat",
        "+++++++" : "parcher",
        ">nosy" : "nosy",
        "La!ser" : "lasher",
        "Ra!ser" : "raiser",
        "spaztik" : "spaztik",
        "_______" : "brandon",
        "magik" : "blackmagik",
        "pixi" : "pixi",
        "prwlr" : "prowler",
        "** dash" : "dash",
        "@blackmagik" : "blackmagik",
        "FisterMiagi" : "deadeye",
        "dresserwood" : "dresserwood",
        "envious//donkey" : "donkey",
        "eternal_" : "eternal",
        "fonze*" : "fonze",
        "|___---___---___|" : "parcher",
        "ETCW.PRWLR" : "prowler",
        "Ra!ser-D" : "raiser",
        "BRND" : "brandon",
        "f000nzeeee" : "fonze",
        "fenix" : "fenix",
        "nigel" : "nigel",
        "siluro" : "siluro",
        "jaytee" : "jaytee",
        "donkz" : "donka",
        "76F" : "76f",
        "m?les" : "miles",
        "rob" : "rob",
        "smellsa" : "elsa",
        "Cypher" : "cypher",
        "MILES" : "miles",
        "PARCHER" : "parcher",
        "murkeeeeeeeee" : "murkey",
        "dresserwood!" : "dresserwood",
        "c@k-el" : "cakel",
        "Du5t3r" : "duster",
        "<3 caffeine" : "caffeine",
        "f'WarRi0R" : "warrior",
        ".whizzard" : "whizzard",
        "00`rob" : "rob",
        "murkey" : "murkey",
        "sloth*" : "sloth",
        "reker" : "reker",
        "miles l-|===>--" : "miles",
        "Wang of Pain" : "wang",
        "EZCLAPS BRU" : "bru",
        "EZCLAPS donka" : "donka",
        "EZCLAPS fro :O(" : "fro",
        "EZCLAPS miles" : "miles",
        "EZCLAPS source" : "source",
        "c@kmas" : "cakel",
        "EZCLAPSFisterMiagi" : "deadeye",
        "Fistermiagi" : "deadeye",
        "tr@gmas" : "tragic",
        "bigdonk$eren!ty" : "raiser",
        "bigdonkconscious*" : "conscious",
        "bigdonkdonkey" : "donkey",
        "bigdonkdonkz" : "donka",
        "bigdonkfenix" : "fenix",
        "bigdonkspaztik" : "spaztik",
        "blackpool f0nze" : "fonze",
        "blackpool fro" : "fro",
        "blackpool john_mullins" : "john_mullins",
        "blackpool murkey" : "murkey",
        "blackpool ping" : "pingrage",
        "blackpool rob" : "rob",
        "LASHER" : "lasher",
        "blecky g" : "elsa",
        "donkey(+)" : "donkey",
        "vis" : "vis",
        "$eren!ty-D" : "raiser",
        "planet" : "parcher",
        "Wolfplayer4" : "parcher",
        "booneco.buthole" : "deadeye",
        "three kittens" : "donkey",
        "O.G.FiddyMiagi$$" : "deadeye",
        "$$young$$spazy$$" : "spaztik",
        "$dIRTy$D$" : "donkey",
        "$mAdmoNey$murkey" : "murkey",
        "$nein2funf$donk" : "donka",
        "ARISWU" : "aristotle",
        "DjFloggyFlog..." : "flogzero",
        "$$fr$sh$$f0nz$$$" : "fonze",
        "Lil Johnny_Mill1000000n" : "john_mullins",
        "Ol'DustyBastard" : "duster",
        "ProjectParch" : "parcher",
        "MEANMUGGIN" : "mean",
        "WolfPlayer5" : "parcher",
        "$$DiggitySeren$$" : "raiser",
        "$$DiggitySeren$$G" : "raiser",
        "[>>] Cliffdark" : "cliffdark",
        "conscious*" : "conscious",
        "Flogzero" : "flogzero",
        "fonze" : "fonze",
        "fromon:O(" : "fro",
        "DillWeed" : "dillweed"
        }

renames["2020Sep"] = {
        "CLEVERMEAN" : "mean",
        "CLEVER pink" : "CLEVER pink",
        "c@k-el*" : "cakel",
        "fistermiagi" : "deadeye",
        "CLEVER reker" : "reker",
        "name" : "parcher",
        "CLEVER murkey" : "murkey",
        "John_Mullins" : "john_mullins",
        "donkey&" : "donkey",
        "CLEVER fonze*" : "fonze",
        "CORONAROB" : "rob",
        "eXe|Flogzero" : "flogzero",
        "CLEVER $eren!ty" : "raiser",
        "CLEVER Du5t3r" : "duster",
        "ShaT" : "shat",
        "CLEVER spaztik" : "spaztik",
        "CLEVER" : "CLEVER",
        "eternal_" : "eternal",
        "Du5t3r" : "duster",
        "FisterMiagi" : "deadeye",
        "asce-el" : "murkey",
        "bru" : "bru",
        "c@k-el" : "cakel",
        "donkey" : "donkey",
        "dresserwood!" : "dresserwood",
        "f0nz3*" : "fonze",
        "miles" : "miles",
        ".c@k-el" : "cakel",
        "SOURCE" : "source",
        "[MAGA] donkey" : "donkey",
        "fonze*" : "fonze",
        "lijmbal" : "lijmbal",
        "spaztik" : "spaztik",
        "$eren!ty-D" : "raiser",
        "N/AFistermiagi" : "deadeye",
        "eXe|Mean" : "mean",
        "$eren!ty*" : "raiser",
        "ETERNAL" : "eternal",
        "source*" : "source",
        "Seren!ty" : "raiser",
        "[MAGA] Prwlr" : "prowler",
        "brujah" : "bru",
        "fromon" : "fro",
        "lame" : "lamelame",
        "fromiam" : "fro",
        "prwlr" : "prowler",
        "same" : "samesame",
        "BLM SOURCE" : "source",
        "BLM c@k" : "cakel",
        "BLM donkey" : "donkey",
        "BLM donkz" : "donka",
        "BLM margaREKa" : "reker",
        "BLM spaztik" : "spaztik",
        "Slade" : "slade",
        "WM1$eren!ty" : "raiser",
        "WM1Du5t3r" : "duster",
        "WM1ETERNAL" : "eternal",
        "WM1Fistermiagi" : "deadeye",
        "WM1LES" : "miles",
        "WMURKEY" : "murkey",
        "WMf0nze*" : "fonze",
        "[uR]-xNoleet-" : "xNoleet",
        "-[x]-DeadEye" : "deadeye",
        "@blackmagik" : "blackmagik",
        "Kittens" : "kittens",
        "d[_]nkey" : "donkey",
        "d[_]onka" : "donka",
        "f[_]onze*" : "fonze",
        "game" : "vis",
        "FONZE" : "fonze",
        "rittersport" : "fro",
        "jaytee" : "jaytee",
        "vis" : "vis",
        "donkz":"donka",
        "AutumnJT" : "jaytee",
        "Canopy Lasher" : "lasher",
        "DeadLeaf DillWeed" : "dillweed",
        "Hedges donkey" : "donkey",
        "John_TorontoMapleLeafs_Mullin" : "john_mullins",
        "PreSpringDu5t3r" : "duster",
        "ROB" : "rob",
        "Ra!ser-D" : "raiser",
        "donka" : "donka",
        "murkey" : "murkey",
        "no foliage fonze" : "fonze",
        "shrubconscious*" : "conscious",
        "Dead Eye" : "deadeye",
        "eternal" : "eternal",
        "rob" : "rob",
        "DeadEye" : "deadeye",
        "DozA" : "doza",
        "magiklicksballs" : "blackmagik",
        "dresserwoodisahomo" : "dresserwood",
        "fro-el" : "fro",
        "no flora fonze" : "fonze",
        "DillWeed" : "dillweed",
        "eternaL" : "eternal",
        "nigel" : "nigel",
        "qak-l" : "cakel",
        "rekernugz" : "reker",
        "Becky G" : "elsa",
        "dresserwood" : "dresserwood",
        "festus" : "festus",
        "Joep" : "joep",
        "fro" : "fro",
        "@TeddyKGB" : "deadeye",
        "c@kzik" : "cakel",
        "Dillzik" : "dillweed",
        "@fonzeKGB" : "fonze",
        "@murkey" : "murkey",
        "@RobMI6" : "rob",
        "@Ra!serKGB" : "raiser",
        "@bruKGB" : "bru",
        "donkzik" : "donka",
        "@@@@@@@donkey @ @" : "donkey",
        "@mooshuKGB" : "mooshu",
        "@dwood!" : "dresserwood",
        "S|A BrianN" : "sa-brian",
        "WolfPlayer19" : "wolfplayer19",
        "Leafy donkey" : "donkey",
        "iIi pingrage" : "pingrage",
        "8===D$eren!ty" : "raiser",
        "foliage fonze" : "fonze",
        "8===dDill" : "dillweed",
        "crumbs" : "crumbs"
        }

renames["2020Oct"] = {
        "Du5t3r" : "duster",
        "John_Mullins" : "john_mullins",
        "Ra!ser-D" : "raiser",
        "ShaT" : "shat",
        "donkzik" : "donka",
        "eternal" : "eternal",
        "festus" : "festus",
        "fonze" : "fonze",
        "fro" : "fro",
        "magik" : "blackmagik",
        "miles" : "miles",
        "reker" : "reker",
        "spaztik" : "spaztik",
        "BORRIS BOB" : "rob",
        "Becky G" : "elsa",
        "PUTIN spaztik" : "spaztik",
        "Reagan-c@k" : "cakel",
        "TREDEAUAU donka" : "donka",
        "bru" : "bru",
        "fonze*" : "fonze",
        "murkey" : "murkey",
        "donkey" : "donkey",
        "eternal_" : "eternal",
        "@anonimity" : "blackmagik",
        "FisterMiagi" : "deadeye",
        "Kittens" : "kittens",
        "parcher" : "parcher",
        "Qak-l" : "cakel",
        "[p] bru" : "bru",
        "[p] eternal" : "eternal",
        "[p] spaztik" : "spaztik",
        "[pw2] donkey" : "donkey",
        "[pw2]fonze*" : "fonze",
        "anon" : "blackmagik",
        "coloureternal" : "eternal",
        "knickersspaztik" : "spaztik",
        "plonkerdonker" : "donkey",
        "WankerFonze" : "fonze",
        "prwlr" : "prowler",
        "SOURCE" : "source",
        "scrill4 :/" : "scrilla",
        "Wang of Pain" : "wang",
        "paws" : "paws",
        "donkz" : "donka",
        "DNK" : "donkey",
        "fromiam" : "fro",
        "@Br!ann" : "brian",
        "BRND" : "brandon",
        "pumpkin" : "pumpkin",
        "WHIZZ THE KID" : "whizz",
        "S|A BrianN" : "briann",
        "TRNL" : "eternal",
        "[TRO]DillWeed" : "dillweed",
        "[TRO]Du5t3r" : "duster",
        "[TRO]Ra!ser" : "kaiser",
        "[TRO]c@k" : "cakel",
        "[TRO]donka" : "donka",
        "[TRO]mooshu" : "mooshu",
        "[TRO]trraagggg" : "tragic",
        "[tro]magik" : "blackmagik",
        "spztk" : "spaztik",
        "<<Druwin>>" : "druwin",
        "<<John_Mullins>>" : "john_mullins",
        "<<Ra!ser>>" : "kaiser",
        "<<jamZz>>" : "jam",
        "<<la-drunk-sher>>" : "lasher",
        "<<p r w l r>>" : "prowler",
        "MILES" : "miles",
        "donkEy" : "donkey",
        "<<<fonze>>>" : "fonze",
        "F.M. Donkey" : "donkey",
        "F.M. Life" : "fmlife",
        "F.M. eternal" : "eternal",
        "F.M. fonze*" : "fonze",
        "F.M. spaztik" : "spaztik",
        "F.M. c@k" : "cakel",
        "mooshu" : "mooshu",
        "BRU" : "bru",
        "ELSA H" : "elsa",
        "Eter_al" : "eternal",
        "FESTUS" : "festus",
        "Fonz_e*" : "fonze",
        "KITTENS" : "kittens",
        "MOOSHU" : "mooshu",
        "Prwlr_nL" : "prowler",
        "SPAZTIK" : "spaztik",
        "c@k_el" : "cakel",
        "Festus^ '.'" : "festus",
        "im[jamZz]" : "jam",
        "nigel" : "nigel",
        "8====D" : "blackmagik",
        "AWWW donka" : "donka",
        "AWWW source" : "source",
        "AWWW Dwo0d!" : "dresserwood",
        "MANE Becky" : "elsa",
        "MANE festus'.'" : "festus",
        "MANE Fistermiagi" : "deadeye",
        "MANE fonze*" : "fonze",
        "MANE John_Mullins" : "john_mullins",
        "AWWw c@k" : "cakel",
        "AWWW  bru" : "bru",
        "AWWW fro" : "fro",
        "AWWW mooshu" : "mooshu",
        "MANE murkey" : "murkey",
        "MANE spaztik" : "spaztik",
        "Becky" : "elsa",
        "MUZZLE BRND" : "brandon",
        "RFRERAEFRSFDSF" : "nobody1",
        "MUZZLE KITTENS" : "kittens",
        "MUZZLE fest" : "festus",
        "MUZZLE fonze*" : "fonze",
        "MUZZLE pING" : "ping",
        "Donkey o/" : "donkey",
        "donka" : "donka",
        "eternalzZZzZ" : "eternal",
        "fromon :O)" : "fro",
        "jamZz D:" : "jam",
        "mooshunNNnN" : "mooshu",
        "nigel >:I" : "nigel",
        "DresserWood!" : "dresserwood",
        "FESTUSzZZzZ" : "festus",
        "JoepzzzZ" : "joep",
        "raw! rAzZ" : "druwin",
        "{::IBRUI::}" : "bru",
        "{::IFESI::}" : "festus",
        "{::|DNK|::}" : "donkey",
        "{::|MGK|::}" : "blackmagik",
        "{::|TRNL|::}" : "eternal",
        "[::IFRMI::}" : "fro",
        "Donkey" : "donkey",
        "D|S-Magik" : "blackmagik",
        "umarxistdouche" : "deadeye",
        "<<Robes>>" : "rob",
        "@murkey" : "murkey",
        "c@k-el" : "cakel",
        "jaytee" : "jaytee",
        "eternalzZzzZ" : "eternal",
        "Spaztik" : "spaztik",
        "sleepy" : "parcher",
        "rumchocolate-41off" : "cholo",
        "AWMAHGAWD donkey" : "donkey",
        "AWMAHGAWD fonze" : "fonze",
        "AWMAHGAWD miles" : "miles",
        "AWMAHGAWD mooshu" : "mooshu",
        "AWMAHGAWD nigel" : "nigel",
        "AWMAHGAWD source" : "source",
        "raw! razz" : "druwin",
        "source" : "source",
        "!noadd @Fister" : "deadeye",
        "!noadd @bru" : "bru",
        "!noadd @eternal" : "eternal",
        "!noadd @fro" : "fro",
        "!noadd @jamZz" : "jam",
        "!noadd @miles" : "miles",
        "[<<] Donkey" : "donkey",
        "[<<] Druwin" : "dwuwin",
        "[<<] Du5t3r" : "duster",
        "[<<] Fonze" : "fonze",
        "parcher." : "parcher",
        "DillWeed" : "dillweed",
        "rekerneversober" : "reker",
        "trraaagggg" : "tragic",
        "Flogzero..." : "flogzero",
        "@CypherDill" : "dillweed",
        "@everyone Mullins" : "john_mullins",
        "@everyonespaztik" : "spaztik",
        "@uUmm fbl" : "fbl",
        "unlockteams" : "parcher",
        "TeammilesFister" : "miles",
        "Jimmy" : "pasek",
        "TEAMMILESJOEP" : "joep",
        "tEAMmILESmILES" : "miles",
        "teamNIGELfro" : "fro",
        "teammilessource" : "source",
        "@donkaFonze*" : "fonze",
        "@spaz-c@k" : "cakel",
        "TEAMCAFFRa!ser" : "raiser",
        "lolol" : "druwin",
        }

renames["2020Nov"] = {
        "#freemurkey." : "murkey",
        "DllWd" : "dillweed",
        "John_Mullins" : "john_mullins",
        "MANE FisterMiagi" : "deadeye",
        "MANE Ra!ser" : "raiser",
        "MANE c@k" : "cakel",
        "MANE eternal" : "eternal",
        "MANE jaytee" : "jaytee",
        "MANE spaztik" : "spaztik",
        "ShaT" : "shat",
        "bru" : "bru",
        "donka" : "donka",
        "fonze" : "fonze",
        "jimbo" : "pasek",
        "moshu" : "mooshu",
        "parcher" : "parcher",
        "prwlr" : "prowler",
        "Fentanyl!" : "fetanyl",
        "Fistermiagi" : "deadeye",
        "Jimmy" : "pasek",
        "KimK2020 #MABA" : "elsa",
        "Kittens" : "kittens",
        "Ra!ser" : "raiser",
        "Ra!ser-D" : "raiser",
        "SOURCE" : "source",
        "Wang of Pain" : "wang",
        "c@k-el" : "cakel",
        "knife" : "knifey",
        "miles" : "miles",
        "mooshu" : "mooshu",
        "p2nkst1nk Rek" : "reker",
        "quiero taco bell" : "murkey",
        "scrill4 :/" : "scrilla",
        "spaztik" : "spaztik",
        "#FreeMullins Jimmy" : "pasek",
        "John M.GUid" : "parchlias",
        "John_Mullins #FREEPARCHER" : "john_mullins",
        "buck fubba" : "buck fubba",
        "Du5t3r" : "duster",
        "fonze*" : "fonze",
        "Donkey" : "donkey",
        "conscious*" : "conscious",
        "shootz" : "shootz",
        "Becky G" : "elsa",
        "ETERNAL" : "eternal",
        "Fox" : "fox",
        "Fro:O(" : "fro",
        "N|A John_Gringo" : "john_mullins",
        "Ra!ser]]]" : "raiser",
        "SOURCE!!!" : "source",
        "c@k-el:/" : "cakel",
        "nigel]]]" : "nigel",
        "o prwlr" : "prowler",
        "spaztik]]" : "spaztik",
        "Burro :>" : "donkey",
        "Eslemsil" : "miles",
        "FisterMiagi" : "deadeye",
        "h2o" : "h2o",
        "Boo7y" : "booty",
        "m" : "john_mullins",
        "AMATEUR.ETERNAL" : "eternal",
        "AMATEUR.FONZE" : "fonze",
        "AMATEUR.FRO:O(" : "fro",
        "AMATEUR.Fox" : "fox",
        "AMATEUR.MILES" : "miles",
        "AMATEUR.prwlr" : "prowler",
        "caff" : "caffeine",
        "Fest2o" : "festus",
        "faddsaasd" : "risk",
        "brutrolig" : "utrolig",
        "nigel" : "nigel",
        "recount-doNka" : "donka",
        "c@k_Ellins" : "cakel",
        "recount-prwlr" : "prowler",
        "WolfPlayer" : "risk",
        "ZeD:O)" : "zed",
        "cumsock" : "utrolig",
        "Festus!..!" : "festus",
        "Fury-prwlR" : "prowler",
        "Gobble(Ra!ser)" : "raiser",
        "c@ktens" : "cakel",
        "esla" : "elsa",
        "nigel---" : "nigel",
        "spaztik*_*" : "spaztik",
        "'.-.'festus" : "festus",
        "Ra!ser:0(" : "raiser",
        "esla hoks" : "elsa",
        "fromon:O(" : "fro",
        "rek" : "reker",
        "Ra!ser---" : "raiser",
        "eternal" : "eternal",
        "Boo7y :P" : "booty",
        "dT-silenTstorm" : "silentstorm"
        }

renames["2020Dec"] = {
        "Boo7y :P" : "booty",
        "John_Mullins" : "john_mullins",
        "MILES" : "miles",
        "QueenOFMean" : "QueenOFMean",
        "Risk :cwel2:" : "risk",
        "SOURCE!!!" : "source",
        "[>>] Cliffdark" : "cliffdark",
        "c@k-el" : "cakel",
        "esla hoks" : "elsa",
        "eternal" : "eternal",
        "fonze*" : "fonze",
        "mooshu" : "mooshu",
        "00`rob" : "rob",
        "fra-Fes" : "festus",
        "fromon:O(" : "fro",
        "jerk" : "jerk",
        "nizouuuu" : "nizou",
        "parcher" : "parcher",
        "Gorthrax" : "gorthrax",
        "faddsaasd" : "faddsaasd",
        "KrAzYkAzE" : "krazykaze",
        "Rag3&FesTus" : "festus",
        "conscious*" : "conscious",
        "donka" : "donka",
        "reker" : "reker",
        "silenTstorm" : "silentstorm",
        "spaztik" : "spaztik",
        "CHAMPFATiHHH" : "fatihot",
        "FisterMiagi" : "deadeye",
        "Kittens" : "kittens",
        "bru" : "bru",
        "caff" : "caffeine",
        "scrilla" : "scrill4",
        "ALB" : "alb",
        "Burro :>" : "donkey",
        "FonzeMiagi" : "fonze",
        "MilesMiagi" : "miles",
        "donkaMiagi" : "donka",
        "nigelmiagi" : "nigel",
        "Elsa [skipnotify]FIGHT!" : "elsa",
        "///FATiHHHOT" : "fatihot",
        "P.I.M.P." : "pimp",
        "druwin.co.uk" : "druwin",
        "fonze" : "fonze",
        "mLTes" : "miles",
        "@anonimity" : "blackmagik",
        "Fox" : "fox",
        "Yeni :=" : "yeniceri",
        "elsa" : "elsa",
        "h2o" : "h2o",
        "miles" : "miles",
        "Harri Olli" : "Harri Olli",
        "no patience/." : "no patience",
        "MooMiagi" : "MooMiagi",
        "SOURCE" : "source",
        "*<|mooshu" : "mooshu",
        "Blazk" : "blazk",
        "Pipe." : "pipe",
        "conscious.college" : "conscious",
        "n00b" : "noob",
        "spaztik.pro" : "spaztik",
        "*<|source" : "source",
        "*<|c@k-el" : "cakel",
        "*<|eternal" : "eternal",
        "*<|nigel" : "nigel",
        "*<:FisterMiagi" : "deadeye",
        "magik" : "blackmagik",
        "*<|conscious" : "conscious",
        "*<|DillWeed" : "dillweed",
        "eternal_" : "eternal",
        "ASSAULTROB" : "rob",
        "LASHER" : "lasher",
        "nigel" : "nigel",
        "Yeniceri" : "yeniceri",
        "nizmon>:)" : "nizou",
        "donkey" : "donkey",
        "*<|prwlr" : "prowler",
        "nizouuuu?" : "nizou",
        "twi" : "twister",
        "Sam Sperro" : "Sam Sperro",
        "scrill4:/" : "scrill4",
        "source" : "source",
        "FATiHHOT" : "fatihot",
        "Pipe" : "pipe",
        "Roderick" : "murkey",
        "nigel_" : "nigel",
        "prwlr_" : "prowler",
        "source_" : "source",
        "spaztik_" : "spaztik",
        "DillWeed" : "dillweed",
        "c@k-el_" : "cakel",
        "fonze_" : "fonze",
        "siktir lan" : "siktir lan",
        "a bad game" : "a bad game",
        "cnd" : "cnd",
        ":cwel2:" : "risk",
        "Yeniceri_" : "yeniceri",
        "esla" : "elsa",
        "roz'h2o" : "h2o",
        "Druwin" : "druwin",
        "Risk(Q_Q)" : "risk",
        "festus" : "festus",
        "nigel:/" : "nigel",
        "*** Cliffdark" : "cliffdark",
        "*** DozA" : "doza",
        "BRND" : "brandon",
        "Druw_Mullins" : "druwin",
        "Risk 8D" : "risk",
        "MadeInGermany" : "madeingermany",
        "koru" : "koru",
        "pingrage" : "pingrage",
        "Risk" : "risk",
        "q.Druwin<3" : "druwin",
        "/>ingrage" : "pingrage",
        "mooshuNOcommie" : "mooshu",
        "OuiOui festus" : "festus",
        "prWlr" : "prowler",
        "!tH!jaytee" : "jaytee",
        "2021 Kittens" : "kittens",
        "2021 donka" : "donka",
        "2021 eternal" : "eternal",
        "2021 prwlr" : "prowler",
        "ICI C'EST PARIS!" : "ICI C",
        "canhanc" : "canhanc",
        "LCD John_Mullins" : "john_mullins",
        "LCD nigel" : "nigel",
        "LCD parcher" : "parcher",
        "LSD Yeni" : "yeniceri",
        "LCD prwlr" : "prowler",
        "DirtyWhiteBoy" : "DirtyWhiteBoy",
        "REINA" : "reina",
        "elver" : "elver",
        "ESLA" : "elsa",
        "//pingrage" : "pingrage",
        "p2nkst1nk reker" : "reker",
        "Snillum_Nhoj" : "john_mullins",
        "Ka!seR" : "kaiser",
        "ResiaK" : "kaiser",
        }

renames["eu\gsix"] = {
        "BRND" : "brandon",
        "Donkey o/" : "donkey",
        "FATiHHOTTTTTTTT" : "fatihot",
        "Joep." : "joep",
        "Plaz" : "plaz",
        "bully." : "bully",
        "haaizor." : "haaizor",
        "mata." : "mata",
        "parcher" : "parcher",
        "CliffZz" : "cliffdark",
        "Enigma" : "enigma",
        "Jin.=E" : "jin",
        "Plaz.=)" : "plaz",
        "froZz" : "fro",
        "jamZz" : "jam",
        "syL" : "syl",
        "torZz" : "toryu",
        "utrolig.:x" : "utrolig",
        "$ Adlad" : "adlad",
        "$ Enigma" : "enigma",
        "$ canhanc" : "canhanc",
        "$ jd" : "jd",
        "$ ozzmosis" : "ozzmosis",
        "Grcs" : "graecos",
        "Ra!ser" : "raiser",
        "$ crabje" : "crabje",
        "Yeniceri" : "yeniceri",
        "<<=KEVIN=@@@" : "kevin",
        "Graecos" : "graecos",
        "Mirage" : "mirage",
        "Toryu" : "toryu",
        "fromiam" : "fro",
        "mouly" : "mouly",
        "B: delgon" : "delgon",
        "D: Yeniceri" : "yeniceri",
        "Jin." : "jin",
        "L: goatsex" : "goatsex",
        "O: Lasher" : "lasher",
        "P: Ra!ser" : "raiser",
        "X: crumbs" : "crumbs",
        "frO.:O)" : "fro",
        "sAilor." : "sailor",
        "sonn3t." : "sonnet",
        "syL." : "syl",
        "<o/ homie" : "homie",
        "DiT!" : "ditto",
        "Plaz!" : "plaz",
        "Ra!ser!" : "raiser",
        "Yeniceri!" : "yeniceri",
        "fbl!" : "fbl",
        "xXx sAilor" : "sailor",
        "xXx leonneke" : "leonneke",
        "xxx Jin =x" : "jin",
        "xxx John_Mullins" : "john_mullins",
        "xxx fro:O)" : "fro",
        "Adlad" : "adlad",
        "Cliffdark" : "cliffdark",
        "Jin" : "jin",
        "John_Mullins" : "john_mullins",
        "PlazizizFIRREEEE" : "plaz",
        "TORIIIIIIIYUUUUUUUU" : "toryu",
        "UTROBLY:)))))" : "rob",
        "XRBPANZERHOTTTTTT" : "fatihot",
        "yeni" : "yeniceri",
        "<ToRyu>" : "toryu",
        "OmegaIAdlad" : "adlad",
        "OmegaIDiT" : "ditto",
        "OmegaIHaaizor" : "haaizor",
        "OmegaIYeni" : "yeniceri",
        "delgon" : "delgon",
        "homie" : "homie",
        "utrolig" : "utrolig",
        "xMEGA:Plaz" : "plaz",
        "zenix" : "zenix",
        "CliffynatoR :O)" : "cliffdark",
        "Graecos:O)" : "graecos",
        "Joep:O)" : "joep",
        "Torje:O)" : "toryu",
        "X: Enigma" : "enigma",
        "X: MerlinatoR" : "merlinator",
        "X: Plaz" : "plaz",
        "X: nizouuuu" : "nizou",
        "X: sAilor/)" : "sailor",
        "askungen:O)" : "askungen",
        "syL:O)" : "syl",
        "Jack of Diamonds" : "jam",
        "uU Eddo #machine" : "eddo",
        "uU Joep #machine" : "joep",
        "uU crabje #machine" : "crabje",
        "uU haaizor #machine" : "haaizor",
        "uU zenix #machine" : "zenix",
        "uU fbl #machine" : "fbl",
        "Joep" : "joep",
        "X: DiT" : "ditto",
        "X: Graecos" : "graecos",
        "X: Ra!ser" : "raiser",
        "X: Toryu" : "toryu",
        "X: whizz" : "whizz",
        "eternalzZzzZ" : "eternal",
        "..Enigma" : "enigma",
        "..Joep" : "joep",
        "..Ra!ser" : "raiser",
        "..fromon" : "fro",
        "..jd" : "jd",
        "HOMiE" : "homie",
        "SYLERERERERER" : "syl",
        "fbl" : "fbl",
        "Bo0 Ra!ser" : "raiser",
        "Bo0 syL" : "syl",
        "BoO Yeniceri" : "yeniceri",
        "DtTOoOO" : "ditto",
        "bo0 rivjee" : "rivjee",
        "BRND*" : "brandon",
        "OmegaIToryu" : "toryu",
        "WHIZZ THE KID" : "whizz",
        "du$ty" : "dusty",
        "fonze*" : "fonze",
        "nizouuuu))))))))" : "nizou",
        "ATARD DtTO" : "ditto",
        "ATARD JOEP" : "joep",
        "ATARD Yeni" : "yeniceri",
        "ATARD du$ty" : "dusty",
        "ATARD fbl" : "fbl",
        "ATARD mata" : "mata",
        "FRXIC" : "fro",
        "KRXIC" : "kris",
        "TOXIC" : "toxic",
        "prome" : "prometheus",
        "FATiHHOTtTtTtTt" : "fatihot",
        "MIRAGE =]" : "mirage",
        "TORYU :~(" : "toryu",
        "bully" : "bully",
        "froMy:O)" : "fro",
        "ANTIFA-utrolig" : "utrolig",
        "FIFA-Cliffd" : "cliffdark",
        "FIFA-FATiHHOTTT" : "fatihot",
        "FIFA-Joep" : "joep",
        "FIFA-RIVJEE" : "rivjee",
        "FIFA-Toryu ~~~" : "toryu",
        "PES-Druwin" : "druwin",
        "PES-John_Mullins" : "john_mullins",
        "PES-Yeni" : "yeniceri",
        "PES-fbl" : "fbl",
        "PES-fro" : "fro",
        "LASHER @ LIMBO" : "lasher",
        "ZeD @ limbo" : "zed",
        "rivjee @ limbo" : "rivjee",
        "utrolig @ limbo" : "utrolig",
        "[M]toxic" : "toxic",
        "delgon o/" : "delgon",
        "miles" : "miles",
        "yeni :*(" : "yeniceri",
        "(.Y.) whizz" : "whizz",
        "FATiHHOT" : "fatihot",
        "[>>] Cliffdark" : "cliffdark",
        "nizouuuu" : "nizou",
        "puke zed" : "zed",
        "SANDERSutrolig" : "utrolig",
        "TRUMPENIGMA" : "enigma",
        "TRUMPFBL" : "fbl",
        "TRUMPHOMIE" : "homie",
        "TRUMPZeD" : "zed",
        "TRUMPzenix" : "zenix",
        "daryguideADLAD" : "adlad",
        "daryguideGRAECOS" : "graecos",
        "daryguideLASHER" : "dash",
        "daryguideMOULY" : "mouly",
        "daryguideSONNET" : "sonnet",
        "(  .  )(  .  ) Toryu" : "toryu",
        "(.Y.) John_Mullins" : "john_mullins",
        "(.Y.) jd" : "jd",
        "(.Y.) nizouuuu?" : "nizou",
        "(.y.) Jin." : "jin",
        "TRUMPROB" : "rob",
        "ZEEDIERHAAIZOR" : "haaizor",
        "ZEEDIERJOEP" : "joep",
        "ZEEDIERYENI" : "yeniceri",
        "DiT" : "ditto",
        "ZeDiiii" : "zed",
        "crumbs" : "crumbs",
        "FATiH<HOT>" : "fatihot",
        "ZeD #quakenet.org" : "zed",
        "leonneke" : "leonneke",
        "twister" : "twister",
        "Enigma :)" : "enigma",
        "Jin 8O" : "jin",
        "LASHER :x" : "lasher",
        "Webe" : "webe",
        "dictator" : "dictator",
        "sonn3t :o" : "sonnet",
        "ET-Jin" : "jin",
        "ETGraecos" : "graecos",
        "ETdu$ty" : "dusty",
        "ETfaster:3" : "faster",
        "EThomie" : "homie",
        "ETnizouuuu" : "nizou",
        "RtCWAdlad" : "adlad",
        "RtCWLasher?" : "lasher",
        "ETToryu" : "toryu",
        "RtCWutrolig" : "utrolig",
        "rtcwmouly" : "mouly",
        "<=@ dictator" : "dictator",
        "[<<] Yeniceri" : "yeniceri",
        "[<<] dictator" : "dictator",
        "[<<] faster" : "faster",
        "[<<] parcher" : "parcher",
        "[<<] toxic" : "toxic",
        "[>>] utrolig" : "utrolig",
        "snatch.Jin" : "jin",
        "snatch.Mirage" : "mirage",
        "snatch.Toryu" : "toryu",
        "</3 Adlad" : "adlad",
        "</3 Cliffdark" : "cliffdark",
        "</3 DtTO" : "ditto",
        "</3 prometheus" : "prometheus",
        "</3 toxic" : "toxic",
        "</3 utrolig" : "utrolig",
        "FrO from BE" : "fro",
        "KeV from BE" : "kevin",
        "ToR from BE" : "toryu",
        "Webe from FIN" : "webe",
        "ZeD from EE" : "zed",
        "twister from ua" : "twister",
        "</3 Enigma" : "enigma",
        "fromiam999" : "fro",
        "homie1337" : "homie",
        "imEnigma" : "enigma",
        "imJin" : "jin",
        "imZeD" : "zed",
        "imkris" : "kris",
        "imznajda" : "jd",
        "utrolig69" : "utrolig",
        "yeni :/" : "yeniceri",
        "..?Druwin" : "druwin",
        "..?FATiHHoTtTtTt" : "fatihot",
        "..?Jin" : "jin",
        "..?Toryu" : "toryu",
        "..?Yeniceri :)" : "yeniceri",
        "..?utrolig" : "utrolig",
        "Festus" : "festus",
        "ZeD" : "zed",
        "fromon:O(" : "fro",
        "rob" : "rob",
        "lelle!" : "lelle",
        "xrb" : "xrb",
        "xXx goatsex?" : "goatsex",
        "name goatsex!" : "goatsex",
        "X: xrb" : "xrb",
        "..prometheus" : "prometheus",
        "SENGO" : "sengo",
        "Mo0 goatsex" : "goatsex",
        "XRXIC" : "xrb",
        "goatsex!" : "goatsex",
        "xrb!" : "xrb",
        "lelle @ limbo" : "lelle",
        "mystx @ lim" : "mystx",
        "Jimmy" : "jimmy",
        "[M]sengo" : "sengo",
        "ZEEDIERDELGON" : "delgon",
        "wolf3dxrb" : "xrb",
        "snatch.lelle" : "lelle",
        "lelle //" : "lelle",
        "snatch.trolpanzig:O(" : "utrolig",
        }

renames["2021Jan"] = {
        "donkz" : "donka",
        "CLOWN" : "clown",
        "DillWeed" : "dillweed",
        "ESLA" : "elsa",
        "John_Mullins" : "john_mullins",
        "P.I.M.P." : "pimp",
        "Yeniceri" : "yeniceri",
        "c@K2o" : "cakel",
        "ca$HH@-i" : "cash",
        "fESTUS" : "festus",
        "fromon:O(" : "fro",
        "jAm" : "jam",
        "spaztik" : "spaztik",
        "KyLie" : "elsa",
        "Snillum_Nhoj" : "john_mullins",
        "Yeniceri_" : "yeniceri",
        "c@k-el" : "cakel",
        "fonze(s)" : "fonze",
        "jAmmy" : "jam",
        "parcher" : "parcher",
        "spaztik:)" : "spaztik",
        "LCD prwlr" : "prowler",
        "bru" : "bru",
        "Fistermiagi" : "deadeye",
        "Reflection benn" : "reflex",
        "ca$HH" : "cash",
        "donka" : "donka",
        "Eternal!" : "eternal",
        "H.2.O." : "h2o",
        "PARCHER" : "parcher",
        "PRWLR" : "prowler",
        "ROB" : "rob",
        "canhanc" : "canhanc",
        "Blazk" : "blazk",
        "KrAzYkAzE" : "krazykaze",
        "Pipe" : "pipe",
        "Cypher" : "cypher",
        "Lunatic ????" : "luna",
        "SpuddyBuddy" : "spuddy",
        "Virus047" : "virus",
        "caf" : "caffeine",
        "jayt" : "jaytee",
        "rampage" : "rampage",
        "reker" : "reker",
        "FisterMiagi" : "deadeye",
        "Frito" : "bbqfrito",
        "playa" : "playa",
        "Gutz0rz" : "gut",
        "crops" : "corpse",
        "scrill4 :/" : "scrill4",
        "Desk1ciao" : "desk1ciao",
        "PARCHERPANZER" : "parcher",
        "ca$HHH" : "cash",
        "silenTstorm" : "silentstorm",
        "vodka!" : "vodka",
        "SOURCE" : "source",
        "festus!" : "festus",
        "prwlr" : "prowler",
        "Yeni" : "yeniceri",
        "donkey" : "donkey",
        "00`Rob" : "rob",
        "TBK$festus" : "festus",
        "elsa" : "elsa",
        "nizouuuu" : "nizou",
        "walking gun" : "walking gun",
        "rob" : "rob",
        "mooshu" : "mooshu",
        "scrilla" : "scrill4",
        "Reflex cfg <3" : "reflex",
        "Kittens" : "kittens",
        "SuckMyPing" : "ping",
        "fonze" : "fonze",
        "wherearethehitboxes" : "ceres",
        "wherearethehitboxes " : "ceres",
        "eternal" : "eternal",
        "wey-spaztik" : "spaztik",
        "Blazk IG#rtcwchile" : "blazk",
        "ResiaK" : "kaiser",
        "S|A Ka!ser" : "kaiser",
        "Festuz" : "festus",
        "mmb!rd" : "mmbird",
        "nizouuuu?!" : "nizou",
        "pingrage" : "pingrage",
        "Sutsef" : "festus",
        "lanretE" : "eternal",
        "nigel" : "nigel",
        "mmbirdusMaximus" : "mmbird",
        "Festus" : "festus",
        "JAM-Bob" : "JAM-Bob",
        "JAM-Peter" : "JAM-Peter",
        "hosk" : "elsa",
        "uYop*" : "joep",
        "miles" : "miles",
        "corpse" : "corpse",
        "fromiam" : "fro",
        "magik" : "blackmagik",
        "Joep" : "joep",
        "el cadaver" : "elver",
        "rek the spec" : "reker",
        "MILES" : "miles",
        "mmbird" : "mmbird",
        "F.E.S.T.U" : "festus",
        "M.I.L.E.S" : "miles",
        "festus" : "festus",
        "mmc@k!" : "cakel",
        "FIsterMiagi" : "deadeye",
        "S.S." : "dresserwood",
        "h2o" : "h2o",
        "7,7festus" : "festus",
        "ETERNAL,,," : "eternal",
        "BRND" : "brandon",
        "raw.razz" : "druwin",
        "lasher" : "lasher",
        "druwin" : "druwin",
        "dillweed" : "dillweed",
        "esla" : "elsa",
        "D.N.K.Y." : "donkey",
        "pingrage #triggered" : "pingrage",
        "SS" : "dresserwood",
        "fromousehacked" : "fro",
        "jaytee" : "jaytee",
        "WolfPlayer" : "parcher",
        "wolfplayer II" : "deadeye",
        "eternal--->" : "eternal",
        "rekernator" : "reker",
        "Druwin" : "druwin",
        "c@k kent" : "cakel",
        "eagle" : "eagle",
        "fromousepadhacked" : "fro",
        "parcher-mousehackedagain" : "parcher",
        "=DOG=P.I.M." : "pimp",
        "conscious*" : "conscious",
        "AoH.Ka!" : "kaiser",
        "Juan_(Py)" : "Juan_(Py)",
        "jAm:o)" : "jam",
        "!rank Joep" : "joep",
        "!rank c@k-el" : "cakel",
        "!rank eternal" : "eternal",
        "!rank festus" : "festus",
        "!rank fonze" : "fonze",
        "!rank parcher" : "parcher",
        "jam:o)" : "jam",
        "$upac@k" : "cakel",
        "eternal_" : "eternal",
        "AntifaAbrahams" : "AntifaAbrahams",
        "ProudBoy Nancy P." : "ProudBoy Nancy P.",
        "*** $tAhl" : "stahl",
        "ProudGirls Nancy" : "ProudGirls Nancy",
        "Fighter Pilot" : "Fighter Pilot",
        "trashmod" : "parcher",
        "Rep. Shawn Skelly" : "Rep. Shawn Skelly",
        "niwurd" : "druwin",
        "putain" : "putain",
        "Tabarnak" : "festus",
        "connard" : "connard",
        "Deski.cL" : "deski",
        }