renames = {}
renames["2020Feb"] = {
        ".:.c@k-el" :  "cakel",
        ".:.CORPSE" :  "corpse",
        ".:.festus" :  "festus",
        ".:.spaztik" :  "spaztik",
        "[>>] Cliffdark" :  "cliffdark",
        "[tTt]c@k-el" :  "cakel",
        "Aimtastic Shootej" :  "aimtastic",
        "bru" :  "bru",
        "bwat" :  "bwat",
        "caffbe bryant" :  "caffeine",
        "CubanPete" :  "cubanpete",
        "Cypher" :  "cypher",
        "Deadeye" :  "deadeye",
        "DeadEye" :  "deadeye",
        "DHS Cypher" :  "cypher",
        "DHS DeadEye" :  "deadeye",
        "DHS Fistermiagi" :  "deadeye",
        "DHS jaytee" :  "jaytee",
        "DHS REKER" :  "reker",
        "DHS TOMMYTURBO" :  "tragic",
        "DHS tRAGIC" :  "tragic",
        "DillWeed" :  "dillweed",
        "donka" :  "donka",
        "eternal_" :  "eternal",
        "eXe|Anialatem" :  "mean",
        "eXe|Boo7y" :  "booty",
        "eXe|Flogzero" :  "flogzero",
        "FisterMiagi" :  "deadeye",
        "garT" :  "tragic",
        "huckleb rek" :  "reker",
        "HuckleBerryTommy" :  "tragic",
        "Joep" :  "joep",
        "John_Mullins" :  "john_mullins",
        "Kittens" :  "kittens",
        "MoistSurgeon" :  "moistsurgeon",
        "N/A BRND" :  "brandon",
        "N/A CKY" :  "cky",
        "n/a donkey" :  "donkey",
        "N/A DONKZ" :  "donka",
        "n/a eternal" :  "eternal",
        "N/A Ra!ser" :  "raiser",
        "n/a ra!ser" :  "raiser",
        "n00b" :  "n00b",
        "nigel" :  "nigel",
        "parcher" :  "parcher",
        "Ra!ser" :  "raiser",
        "rastareker" :  "reker",
        "rastatommy" :  "tragic",
        "Reflex cfg <3" :  "reflex",
        "RekeR :P" :  "reker",
        "scrill4" :  "scrilla",
        "SnowRunGut" :  "gut",
        "SOURCE" :  "source",
        "spaztik" :  "spaztik",
        "tragiC" :  "tragic",
        "Trinity*c@k-el" :  "cakel",
        "Trinity*festus" :  "festus",
        "Trinity*spaztik" :  "spaztik",
        "tTt->festus" :  "festus",
        "vodka!" :  "vodka"
        }

renames["2020Jan"] = {
        "Cliffdark" :  "cliffdark",
        "Cypher" :  "cypher",
        "DillWeed" :  "dillweed",
        "FisterMiagi" :  "deadeye",
        "Kittens" :  "kittens",
        "P.I.M.P. 180" :  "pimp",
        "Ra!ser" :  "raiser",
        "SOURCE" :  "source",
        "donka" :  "donka",
        "eXe|Boo7y" :  "booty",
        "elsa" :  "elsa",
        "murkey" :  "murkey",
        "reker" :  "reker",
        "spaztik" :  "spaztik",
        "illkilla" :  "illkilla",
        "nigel" :  "nigel",
        "eXe|Anialatem" :  "mean",
        "John_Mullins" :  "john_mullins",
        "[>>] Cliffdark" :  "cliffdark",
        "aaa" :  "parcher",
        "fromiam" :  "fro",
        "-[x]-nigel" :  "nigel",
        "-[x]-spaztik" :  "spaztik",
        "prowler*" :  "prowler",
        "eternal_" :  "eternal",
        "-[x]-DeadEye" :  "deadeye",
        "Festus_of_Pain" :  "festus",
        "MoistSurgeon" :  "moistsurgeon",
        "TK|POW" :  "tkpow",
        "BlewTHAT" :  "raiser",
        "The Ladies Man" :  "ladiesman",
        "Marcus Mariguta" :  "gut",
        "parcher" :  "parcher",
        "eX*Festus" :  "festus",
        "SKOL|Boo7y" :  "booty",
        "Wang of Pain" :  "wang",
        ".:.c@k-el" :  "cakel",
        ".:.prowler" :  "prowler",
        ".:.spaztik" :  "spaztik",
        "eXe|Flogzero" :  "flogzero",
        ".:.Festus" :  "festus",
        "tragiC" :  "tragic",
        "Fistermiagi" :  "deadeye",
        "Hucklebericus" :  "deadeye",
        "c@k-el" :  "cakel",
        "mach1ne" :  "machine",
        "o/ spaztik" :  "spaztik",
        "corpse" :  "corpse",
        "Tittens" :  "tragic",
        ".:.festus" :  "festus",
        "cKy" :  "cky"
        }

renames["2020Mar"] = {
        "!tH!Gut" : "gut",
        "#REDUE John_Mullins" : "john_mullins",
        "-=prowler=-" : "prowler",
        "-Tv-Ra!ser" : "raiser",
        "-eh-brian" : "brian",
        "-n2p)(spaztik" : "spaztik",
        ".:.Flogzero" : "flogzero",
        ".:.c@k-el" : "cakel",
        ".:.crops" : "corpse",
        ".:.festus" : "festus",
        ".:.prowler" : "prowler",
        ".:.spaztik" : "spaztik",
        "BRND REDUE" : "brandon",
        "Cliff of Pain" : "cliffdark",
        "CoronaDill" : "dillweed",
        "Cypher" : "cypher",
        "DHS DEADEYE" : "deadeye",
        "DHS Fistermiagi" : "deadeye",
        "DHS NIGEL" : "nigel",
        "DHS jaytee" : "jaytee",
        "DHS tragiC" : "tragic",
        "DUBARD <o/" : "dubard",
        "Deadeye" : "deadeye",
        "DillWeed" : "dillweed",
        "Festus" : "festus",
        "Fister of Pain" : "deadeye",
        "HuckleBerryTragic" : "tragic",
        "Jimmy" : "jimmy",
        "John_Mullins" : "john_mullins",
        "John_Mullins_of_Pain" : "john_mullins",
        "Kittens" : "kittens",
        "MoistSurgeon" : "moistsurgeon",
        "N/A BRND" : "brandon",
        "N/A Ra!ser" : "raiser",
        "N/A donkz" : "donka",
        "Pasek" : "pasek",
        "Pasek*" : "pasek",
        "Pk of Pain" : "pasek",
        "RAISER" : "raiser",
        "Raiser" : "raiser",
        "SCRILL4" : "scrilla",
        "SOURCE" : "source",
        "Uber Brian" : "kotip",
        "Wang of Pain" : "wang",
        "Yaourt ! ?" : "yaourt",
        "[>>] Cliffdark" : "cliffdark",
        "[>>] Helga von Bulow" : "cliffdark",
        "afk-ternal" : "eternal",
        "bru" : "bru",
        "c@k-el" : "cakel",
        "caffbe bryant" : "caffeine",
        "coronaBRND" : "brandon",
        "dillweed" : "dillweed",
        "donka" : "donka",
        "donkz" : "donka",
        "donkz of  Pain" : "donka",
        "donkztik" : "donka",
        "eXe|Anialatem" : "mean",
        "eXe|Flogzero" : "flogzero",
        "eXe|MeaN" : "mean",
        "eXe|Meanguine" : "mean",
        "eternal_" : "eternal",
        "fisterMiagi" : "deadeye",
        "fromiam" : "fro",
        "fucker" : "raiser",
        "miLes" : "miles",
        "miles" : "miles",
        "miles of Pain" : "miles",
        "mooshu" : "mooshu",
        "murkey" : "murkey",
        "n/a SOURCE" : "source",
        "n/a eternal" : "eternal",
        "n00b" : "brandon",
        "nig of Pain" : "nigel",
        "nigel" : "nigel",
        "parcher" : "parcher",
        "parhcer" : "vis",
        "prowler" : "prowler",
        "reker" : "reker",
        "rekernator" : "reker",
        "roz'murkey" : "murkey",
        "roz'parcher" : "parcher",
        "shootz" : "shootz",
        "source" : "source",
        "spaz of pain" : "spaztik",
        "spaztik" : "spaztik",
        "sscasper" : "casper",
        "tTt-c@k-el" : "cakel",
        "tTt-festus" : "festus",
        "tTt-prowler" : "prowler",
        "teker" : "tragic",
        "v57-sOn4R*" : "sonar",
        ">> Risk!" : "risk",
        "BRND" : "brandon",
        "BoN, Dtto" : "ditto",
        "FisterMiagi" : "deadeye",
        "Flogzero" : "flogzero",
        "Joep" : "joep",
        "LuNa" : "luna",
        "MEAN" : "mean",
        "Raiser clark" : "raiser",
        "TommyTomorrow" : "tragic",
        "boydarilla" : "boydarilla",
        "c@k kent" : "cakel",
        "caff stark" : "caffeine",
        "festus" : "festus",
        "vodka!" : "vodka",
        "tTt-spaztik" : "spaztik",
        "Boydarilla" : "boydarilla",
        "DHS LUNA" : "luna",
        "brujah" : "bru",
        "caff eating" : "caffeine",
        "flogzero" : "flogzero",
        "jaytee***" : "jaytee",
        "kick gut" : "gut",
        "nigel**" : "nigel",
        "raiser" : "raiser",
        "woodChop" : "woodchop"
        }

renames["2020Apr"] = {
        ".:.prowler" : "prowler",
        "Cliffdark" : "cliffdark",
        "DillWeed" : "dillweed",
        "Jimmy" : "pasek",
        "Kittens" : "kittens",
        "NABRND" : "brandon",
        "SOURCE" : "source",
        "bru" : "bru",
        "eXe|Boo7y" : "booty",
        "eXe|Flogzero" : "flogzero",
        "eXe|MeaN" : "mean",
        "eXe|eternal" : "eternal",
        "miles" : "miles",
        "murkey" : "murkey",
        "not13KDAMAGE" : "raiser",
        "parcher" : "parcher",
        "risk" : "risk",
        "spaztik" : "spaztik",
        "tragiC" : "tragic",
        "-playa-" : "playa",
        "Gutzwrzynski" : "gut",
        "Lunatic ????" : "luna",
        "Oops" : "oops",
        "Ra!sa" : "raiser",
        "caff ********" : "caffeine",
        "eXe|donka" : "donka",
        "eXe|prowler" : "prowler",
        "eternal" : "eternal",
        "kotip" : "kotip",
        "paper" : "paper",
        "rozmurk3y" : "murkey",
        "shrek" : "shrek",
        "#REDUE John_Mullins" : "john_mullins",
        "*** Cliffdark" : "cliffdark",
        "*** DozA" : "doza",
        "*** chinamann" : "chinamann",
        "*** sOnAR. <o/" : "sonar",
        "*** schwien" : "schwien",
        "-eh-brian" : "brian",
        ".:.spaztik" : "spaztik",
        "@blackmagik" : "blackmagik",
        "BRND" : "brandon",
        "Boydarilla" : "boydarilla",
        "Cock-El" : "parcher",
        "Cypher" : "cypher",
        "DHS Fistermiagi" : "deadeye",
        "DHS jaytee" : "jaytee",
        "FisterMiagi" : "deadeye",
        "Joep" : "joep",
        "Paint:>" : "paint",
        "RAZERRA!SER" : "raiser",
        "Ra!ser" : "raiser",
        "SCRILL4" : "scrilla",
        "SpuddyBuddy" : "spuddy",
        "TK|POW" : "tkpow",
        "Wang of Pain" : "wang",
        "[>>] Cliffdark" : "cliffdark",
        "aristotle" : "aristotle",
        "blackmagiknc." : "blackmagik",
        "c@k-3l" : "cakel",
        "c@k-el" : "cakel",
        "c@k-el*" : "cakel",
        "d13 caff" : "caffeine",
        "donka" : "donka",
        "donkz" : "donka",
        "eXe|Prowler" : "prowler",
        "festus" : "festus",
        "festusmoelesac" : "festus",
        "flogzero" : "flogzero",
        "gutzzzz" : "gut",
        "jaytee**************" : "jaytee",
        "mooshu" : "mooshu",
        "naper" : "naper",
        "nigel" : "nigel",
        "nigel ***" : "nigel",
        "nigel**" : "nigel",
        "playa" : "playa",
        "proWler" : "prowler",
        "prowler" : "prowler",
        "reker" : "reker",
        "spuddy" : "spuddy",
        "traggart" : "tragic",
        "trag|c" : "tragic",
        "notvis" : "vis",
        "vodka!" : "vodka",
        "-Tv-Ra!ser" : "raiser",
        "c@kztik" : "cakel",
        "-Tv-Conscious*" : "conscious",
        "corpse" : "corpse",
        "blackmagik" : "blackmagik",
        ".=[AoH]BlAZ" : "blaz",
        "jaytee*****" : "jaytee",
        "Ra!ser*" : "raiser",
        "c@k-el***" : "cakel",
        "Flogzero" : "flogzero",
        "OLIOKATH" : "oliokath",
        "RekeR" : "reker",
        "Festusmoesac" : "festus",
        "Cliffdark***" : "cliffdark",
        "mooshu*" : "mooshu",
        "nigel***" : "nigel",
        "trag|C" : "tragic",
        "MeaN" : "mean",
        "knifey" : "knifey",
        "[>>] jaytee" : "jaytee",
        "C0RPSE" : "corpse",
        "CAFF D13" : "caffeine",
        "not blackvis" : "vis",
        "oIiokath" : "oliokath",
        "rekernator" : "reker",
        "woodChop" : "woodchop",
        "Ra!ser ???" : "raiser",
        "brian" : "brian",
        "Ex-)Festus" : "festus",
        "VENOM" : "venom",
        "Euclid" : "euclid",
        "mooshu sux" : "mooshu",
        "eXe|Ra!se" : "raiser",
        "SPEC nigel" : "nigel",
        "fistermiagi" : "deadeye",
        "gut" : "gut",
        "raiser" : "raiser",
        "Tier B Ra!ser" : "raiser",
        "Tier C Jimmy" : "pasek",
        "Tier C c@k" : "cakel",
        "Tier C miles" : "miles",
        "valor-conscious*" : "conscious",
        "Tier C Fistermiagi" : "deadeye",
        "TIER F kotip" : "kotip",
        "Fistermiagi" : "deadeye",
        "bluemagik" : "blackmagik",
        "jaytee'" : "jaytee",
        "gutz0rz" : "gut",
        "Misha X" : "elsa",
        "Conscious*" : "conscious",
        "TIER C SPAZTIK" : "spaztik",
        "nigel." : "nigel",
        "f0nz3*" : "fonze",
        "HyperNegatiVemaN" : "HyperNegatiVemaN",
        "troll fans" : "reflex",
        "// Jimmy" : "pasek",
        "c@kzero" : "cakel",
        "fonze*" : "fonze",
        "c@k" : "cakel"
        }
renames["2020May"] = {
        "@corpse," : "corpse",
        "@jaytee" : "jaytee",
        "Jimmy" : "pasek",
        "MeaN" : "mean",
        "Ra!ser..." : "raiser",
        "beast" : "beast",
        "bru" : "bru",
        "eXe|Flogzero" : "flogzero",
        "fromiam" : "fro",
        "murkey" : "murkey",
        "nigel" : "nigel",
        "prowler" : "prowler",
        "Conscious*" : "conscious",
        "fonze" : "fonze",
        "FisterMiagi" : "deadeye",
        "Kittens" : "kittens",
        "blackmagik" : "blackmagik",
        "c@k-el" : "cakel",
        "donka" : "donka",
        "miles" : "miles",
        "oIiokath" : "oliokath",
        "Dr3sserWo0d!" : "dresserwood",
        "#REDUE John_Mullins" : "john_mullins",
        "DozA" : "doza",
        "festus" : "festus",
        "kindergarden c@k" : "cakel",
        "spaztik" : "spaztik",
        "vodka!" : "vodka",
        "*** Cliffdark" : "cliffdark",
        "Dress3rWo0d!" : "dresserwood",
        "fonze*" : "fonze",
        "blackmagiknc." : "blackmagik",
        "*Conscious'gA" : "conscious",
        "paper" : "paper",
        "eXe|MeaN" : "mean",
        "*Conscious'" : "conscious",
        "Jimmy Bones" : "pasek",
        "corpse" : "corpse",
        "valor-conscious*" : "conscious",
        "pixi" : "pixi",
        "Ra!ser" : "raiser",
        "-n2p)(spaztik-" : "spaztik",
        "$upac@k" : "cakel",
        "c@ktens" : "cakel",
        "asianjaytee" : "jaytee",
        "Jimbo" : "pasek",
        "siTtIns" : "corpse",
        "conscious*" : "conscious",
        "Ra!ser -_-" : "raiser",
        "Anialatem" : "mean",
        "Flogzero" : "flogzero",
        "Pixi" : "pixi",
        "Ra!ser-D" : "raiser",
        "blackmagik)" : "blackmagik",
        "dresserwood!" : "dresserwood",
        "mooshu" : "mooshu",
        "eternal)" : "eternal",
        "spaztik*" : "spaztik",
        "trag|c*" : "tragic",
        "sscasper" : "casper",
        "eXe|Anialatem" : "mean",
        "@festus" : "festus",
        "(503th.esla)" : "elsa",
        "parcher" : "parcher",
        "prwlr-$mG" : "prowler",
        "virus047" : "virus",
        "Cypher" : "cypher",
        "eXe|Folgzero" : "flogzero",
        "eelsa" : "elsa",
        "milse" : "miles",
        "rampage !!!!" : "rampage",
        "caff 23" : "caffeine",
        "playa" : "playa",
        "eternal" : "eternal",
        "Oops" : "oops",
        "reker" : "reker",
        "DillWeed" : "dillweed",
        "MoistSurgeon" : "moistsurgeon",
        "Tittens" : "tragic",
        "Becky G" : "elsa",
        "Cliffdark" : "cliffdark",
        "MILES" : "miles",
        "paper*" : "naper",
        "tragiC" : "tragic",
        "Luna" : "luna",
        "mooshu@" : "mooshu",
        "@eternal)" : "eternal",
        "CORPSE" : "corpse",
        "jaytee" : "jaytee",
        "BRU" : "bru",
        "kotip" : "kotip",
        "prowl3r" : "prowler",
        "dresserwood" : "dresserwood",
        "blackmagik(d)" : "blackmagik",
        "purples.Jimbo" : "pasek",
        "cK aimO" : "aimology",
        "(Daria.Skyhigh)" : "elsa",
        "-d-blackmagik" : "blackmagik",
        "TE)(spaztik" : "spaztik",
        "-a-Ra!ser-)" : "raiser",
        "m|Volks" : "volks",
        "[>>] Daria Cross" : "cliffdark",
        "-a-Ra!ser" : "raiser",
        "[>>] Cliffdark" : "cliffdark",
        "CAFF 23" : "caffeine",
        "Flogzero..." : "flogzero",
        "Mean" : "mean",
        "OIiokath" : "oliokath",
        "donkalabtop" : "donka",
        "gutzzz*" : "gut",
        "trag|c" : "tragic",
        "eternal_" : "eternal",
        "SOURCE" : "source",
        "c@xt0r" : "cakel",
        "n00b" : "noob",
        "MOOSHU" : "mooshu",
        "c@k" : "cakel",
        "dwood" : "woodchop",
        "magik" : "blackmagik",
        "noncefonze" : "fonze",
        "traggart" : "tragic",
        "Joep!" : "joep"
        }

renames["2020MayDraft"] = {
        "8===DBRU" : "bru",
        "8===DFONZ" : "fonze",
        "8===DKittens" : "kittens",
        "8===DMLS" : "miles",
        "8==DFistermiagi" : "deadeye",
        "@blackmagik" : "blackmagik",
        "@c@k-el" : "cakel",
        "@corpse" : "corpse",
        "@eternal)" : "eternal",
        "@festus" : "festus",
        "@nigel" : "nigel",
        "8===DOIiO" : "oliokath",
        "REDUE-Cypher" : "cypher",
        "REDUE-Jimmy" : "pasek",
        "REDUE-Spaztik" : "spaztik",
        "Ra!ser" : "raiser",
        "Redue-Conscious*" : "conscious",
        "Redue-Flogzero" : "flogzero",
        "donka" : "donka",
        "murkey" : "murkey",
        "pixi" : "pixi",
        "rekernator" : "reker",
        "traggart" : "tragic",
        ":+:VirUs047`" : "virus",
        "meaN" : "mean",
        "REDUE-Prowler" : "prowler",
        "Redue-Ra!ser-D^" : "raiser",
        "8===DillWeed" : "dillweed",
        "8===Dknifey" : "knifey",
        "8===DoIiokath" : "oliokath",
        "Dimension" : "dimension",
        "MeaN" : "mean",
        "gart" : "tragic",
        "reker" : "reker",
        "virus" : "virus",
        "8==DFisterMiagi" : "deadeye",
        "beast" : "beast",
        "Redue-Cypher" : "cypher",
        "Redue-Elsa" : "elsa",
        "Redue-Jimmy" : "pasek",
        "Redue-Ra!ser" : "raiser",
        "Redue-Spaztik" : "spaztik",
        "@corpse'" : "corpse",
        "@fromiam" : "fro",
        "@jaytee" : "jaytee",
        "vodka!" : "vodka",
        "[>>] Cliffdark" : "cliffdark"
        }